### PR TITLE
Migrates from pipenv to pip/pyproject.toml

### PR DESCRIPTION
**Pull request by gremid**
As stated in the title; sorry for the pipenv detour, @knit-bee!

Also removed the dependency on `typed-extensions`, as `typing.Self` is part of the Python standard library since v3.11.

Please review!

### CODE REVIEW

**Review by knit-bee — CHANGES_REQUESTED** [review]
The tests for the preprocessing module live in a subdirectory in `wordprofile/preprocessing/tests`.  Running only `pytest` won't execute these tests and they are also ignored in the CI-workflow now. 
I suggest adding the path to `testpaths` in `pyproject.toml` or moving the tests to the main test directory. 
As the preprocessing parts where once more separated, I kept the tests separated as well. Maybe we can drop that distinction, though, as the installation instruction now also suggest a full install.
Otherwise, it looks great to me!

**Comment by gremid** [comment]
Thanks, @knit-bee , I was not paying attention to the preprocessing tests. Will move them to `tests/`.

**Comment by gremid** [comment]
Should be as requested now. I also added the custom spaCy models to the build requirements, so tests and other code can just load them.

**Review by knit-bee — APPROVED** [review]
Looks good to me now. Thanks for the change and your effort in general!

**Pull request merged**
